'use strict';
const T=48,W=19,H=13,canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s),ui={overlay:$('#overlay'),title:$('#modalTitle'),body:$('#modalBody'),play:$('#play'),progress:$('#progress'),lives:$('#lives'),topic:$('#topic'),question:$('#question'),options:$('#options'),toast:$('#toast'),sound:$('#sound'),speed:$('#speedPower'),shield:$('#shieldPower'),teacherBtn:$('#teacherBtn'),teacherPanel:$('#teacherPanel'),teacherGrid:$('#teacherGrid'),closeTeacher:$('#closeTeacher'),teacherLogin:$('#teacherLogin'),teacherLoginForm:$('#teacherLoginForm'),teacherPassword:$('#teacherPassword'),teacherLoginError:$('#teacherLoginError'),teacherCancel:$('#teacherCancel')};
const topics=['Đưa thừa số ra ngoài dấu căn','Đưa thừa số vào trong dấu căn','Trục căn thức ở mẫu','Rút gọn biểu thức chứa căn'];
// Each item: prompt, expression, four choices, correct index, worked equation.
const raw=[
['Rút gọn','√50',['5√2','25√2','2√5','10√5'],0,'√50 = 5√2'],
['Rút gọn','√72',['4√3','8√2','6√2','12√2'],2,'√72 = 6√2'],
['Rút gọn','√98',['7√2','14√7','2√7','49√2'],0,'√98 = 7√2'],
['Với a ≥ 0, tính','√(12a²)',['6a√2','2a√3','4a√3','2a²√3'],1,'√(12a²) = 2a√3'],
['Với a ≤ 0, tính','√(25a²)',['5a','-5a','25a²','-25a'],1,'√(25a²) = -5a'],
['Rút gọn','√200',['20√5','10√2','5√8','2√10'],1,'√200 = 10√2'],
['Đưa vào dấu căn','2√3',['√6','√12','√9','√5'],1,'2√3 = √12'],
['Đưa vào dấu căn','4√2',['√8','√16','√32','√24'],2,'4√2 = √32'],
['Đưa vào dấu căn','3√5',['√15','√45','√35','√90'],1,'3√5 = √45'],
['Với a ≥ 0, đưa vào dấu căn','a√7',['√(7a)','√(7a²)','√(a²+7)','a√49'],1,'a√7 = √(7a²)'],
['Đưa vào dấu căn','5√3',['√15','√45','√75','√125'],2,'5√3 = √75'],
['Với a ≥ 0, đưa vào dấu căn','2a√5',['√(10a)','√(20a²)','√(20a)','√(4a²+5)'],1,'2a√5 = √(20a²)'],
['Trục căn thức ở mẫu','1/√2',['√2/2','2√2','1/2','√2'],0,'1/√2 = √2/2'],
['Trục căn thức ở mẫu','2/√5',['√5/2','2√5/5','√10/5','5√2/2'],1,'2/√5 = 2√5/5'],
['Trục căn thức ở mẫu','5/(2√5)',['2√5','√5/2','5√5','√5/5'],1,'5/(2√5) = √5/2'],
['Trục căn thức ở mẫu','1/(√5 - 2)',['√5 - 2','1/(√5 + 2)','√5 + 2','(√5 + 2)/5'],2,'1/(√5 - 2) = √5 + 2'],
['Trục căn thức ở mẫu','2/(√3 + 1)',['√3 + 1','√3 - 1','2√3 - 1','(√3 - 1)/2'],1,'2/(√3 + 1) = √3 - 1'],
['Trục căn thức ở mẫu','1/(2 + √3)',['2 - √3','2 + √3','√3 - 2','1/(2 - √3)'],0,'1/(2 + √3) = 2 - √3'],
['Rút gọn','√12 + √27',['7√3','5√3','3√39','15'],1,'√12 + √27 = 5√3'],
['Rút gọn','2√8 + √18',['5√2','7√2','6√2','2√26'],1,'2√8 + √18 = 7√2'],
['Rút gọn','√45 - √20',['√5','5√5','√25','-√5'],0,'√45 - √20 = √5'],
['Tính','√3(√12 + √27)',['5','15','5√3','9'],1,'√3(√12 + √27) = 15'],
['Tính','(√7 + √2)(√7 - √2)',['9','5','√5','7'],1,'(√7 + √2)(√7 - √2) = 5'],
['Rút gọn','√50 + √8 - √18',['4√2','3√2','7√2','4√3'],0,'√50 + √8 - √18 = 4√2']
];
const questions=raw.map((r,i)=>({topic:topics[Math.floor(i/6)],lead:r[0],expr:r[1],choices:r[2],answer:r[3],work:r[4]}));
const doors=[[3,3],[15,3],[3,9],[15,9]],doorColors=['#72efff','#ffbd72','#c5a7ff','#96f5b7'];
const worlds=[{name:'THƯ VIỆN PHA LÊ',floor:'#1a304a',floor2:'#203d56',wall:'#385476',wall2:'#466486',accent:'#72eaff',particle:'#b8ffff',shape:0},{name:'HẦM LỬA LÂN TINH',floor:'#302637',floor2:'#432a3c',wall:'#694558',wall2:'#835063',accent:'#ffae74',particle:'#ffe09a',shape:1},{name:'VƯỜN RỄ CỔ',floor:'#183539',floor2:'#244345',wall:'#35615c',wall2:'#41786a',accent:'#a9efac',particle:'#c6ffd5',shape:2},{name:'ĐIỆN SAO TÍM',floor:'#24273e',floor2:'#302d50',wall:'#514b78',wall2:'#686293',accent:'#c5a8ff',particle:'#e7d0ff',shape:3}];
let grid=Array.from({length:H},()=>Array(W).fill(1)),player={x:9.5*T,y:6.5*T},enemies=[],particles=[],phase='menu',previousPhase='menu',index=0,lives=3,invuln=0,keys=new Set(),last=0,nowFrame=0,toastUntil=0,audioCtx,soundOn=true,wrongDoor=-1,world=worlds[0],stageNotice=0,playerFacing=1,joystick={x:0,y:0,pointer:null},correctCount=0,speedCharges=0,shieldCharges=0,speedTime=0,shieldTime=0;
function seeded(seed){let s=seed>>>0;return()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296}}
function buildMaze(stage){const rng=seeded(17171+stage*9931);const a=Array.from({length:H},()=>Array(W).fill(1));const seen=new Set(),stack=[[9,5]];a[5][9]=0;seen.add('9,5');while(stack.length){const [x,y]=stack[stack.length-1],opts=[];for(const [dx,dy] of [[0,2],[2,0],[0,-2],[-2,0]]){let xx=x+dx,yy=y+dy;if(xx>=1&&xx<=17&&yy>=1&&yy<=11&&!seen.has(xx+','+yy))opts.push([xx,yy,dx,dy])}if(!opts.length){stack.pop();continue}const [xx,yy,dx,dy]=opts[Math.floor(rng()*opts.length)];a[y+dy/2][x+dx/2]=0;a[yy][xx]=0;seen.add(xx+','+yy);stack.push([xx,yy])}
for(const [x1,y1,x2,y2] of [[1,1,5,4],[13,1,17,4],[1,8,5,11],[13,8,17,11]])for(let y=y1;y<=y2;y++)for(let x=x1;x<=x2;x++)a[y][x]=0;
a[6][9]=0;a[5][9]=0;a[7][9]=0;return a}
function cell(x,y){return x>=0&&y>=0&&x<W&&y<H&&grid[y][x]===0}function reachable(x,y,r=12){return [[-r,-r],[r,-r],[-r,r],[r,r]].every(([dx,dy])=>cell(Math.floor((x+dx)/T),Math.floor((y+dy)/T)))}function move(o,dx,dy,r=12){if(reachable(o.x+dx,o.y,r))o.x+=dx;if(reachable(o.x,o.y+dy,r))o.y+=dy}
function tile(o){return[Math.max(0,Math.min(W-1,Math.floor(o.x/T))),Math.max(0,Math.min(H-1,Math.floor(o.y/T)))]}
function path(from,to){const [sx,sy]=tile(from),[tx,ty]=tile(to),q=[[sx,sy]],seen=new Set([sx+','+sy]),back=new Map();for(let i=0;i<q.length;i++){const [x,y]=q[i];if(x===tx&&y===ty){let cur=tx+','+ty;while(back.get(cur)!==sx+','+sy&&back.has(cur))cur=back.get(cur);return cur.split(',').map(Number)}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const a=x+dx,b=y+dy,k=a+','+b;if(cell(a,b)&&!seen.has(k)){seen.add(k);back.set(k,x+','+y);q.push([a,b])}}}return[sx,sy]}
function spawnStage(){grid=buildMaze(index);world={...worlds[index%4],accent:`hsl(${(195+index*37)%360} 90% 75%)`,particle:`hsl(${(175+index*37)%360} 95% 85%)`,shape:index%6};player={x:9.5*T,y:6.5*T};keys.clear();resetJoystick();wrongDoor=-1;invuln=1.8;stageNotice=2.1;lives=3;speedTime=0;shieldTime=0;updateLives();updatePowers();let rng=seeded(index*8137+519),candidates=[];for(let y=1;y<H-1;y++)for(let x=1;x<W-1;x++)if(cell(x,y)&&Math.abs(x-9)+Math.abs(y-6)>7&&doors.every(([a,b])=>Math.abs(a-x)+Math.abs(b-y)>2))candidates.push([x,y]);enemies=[];const count=3+Math.min(2,Math.floor(index/8));for(let i=0;i<count;i++){let choice=candidates.splice(Math.floor(rng()*candidates.length),1)[0]||[1+i,1];enemies.push({x:(choice[0]+.5)*T,y:(choice[1]+.5)*T,kind:i%3,pace:78+(index%6)*3+(i%3)*8,target:null,repath:0,phase:rng()*6.28})}particles=Array.from({length:22+(index%6)*3},(_,i)=>({x:rng()*W*T,y:rng()*H*T,s:1+rng()*2.3,offset:rng()*6.28,kind:i%4}));document.documentElement.style.setProperty('--stage-accent',world.accent);ui.topic.textContent=questions[index].topic;ui.progress.textContent=`${index+1}/${questions.length}`;ui.question.innerHTML=`${questions[index].lead} ${math(questions[index].expr)} ?`;ui.options.innerHTML=questions[index].choices.map((o,i)=>`<span class="opt" style="border-left-color:${doorColors[i]}"><b>${'ABCD'[i]}</b> ${math(o)}</span>`).join('')}
function updateLives(){ui.lives.textContent='♥'.repeat(lives)+'♡'.repeat(3-lives)}
function music(freq=500,dur=.1,type='sine'){if(!soundOn)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.065,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch{}}
// MathML gives radicals a proper full-width vinculum and displays rationalized fractions.
function atom(s){let out='';for(let i=0;i<s.length;){const c=s[i];if(c==='√'){i++;let inside='';if(s[i]==='('){let depth=1;i++;while(i<s.length&&depth){if(s[i]==='(')depth++;else if(s[i]===')')depth--;if(depth)inside+=s[i];i++}}else while(i<s.length&&/[0-9a-zA-Z²]/.test(s[i]))inside+=s[i++];out+=`<msqrt>${atom(inside)}</msqrt>`}else if(/[0-9]/.test(c)){let n='';while(i<s.length&&/[0-9]/.test(s[i]))n+=s[i++];out+=`<mn>${n}</mn>`}else if(/[a-zA-Z]/.test(c)){i++;out+=s[i]==='²'?`<msup><mi>${c}</mi><mn>2</mn></msup>`:`<mi>${c}</mi>`;if(s[i]==='²')i++}else{out+=`<mo>${c==='<'?'&lt;':c==='&'?'&amp;':c}</mo>`;i++}}return out}
function math(s){let level=0,slash=-1;for(let i=0;i<s.length;i++){if(s[i]==='(')level++;else if(s[i]===')')level--;else if(s[i]==='/'&&level===0){slash=i;break}}const body=slash<0?atom(s):`<mfrac><mrow>${atom(s.slice(0,slash))}</mrow><mrow>${atom(s.slice(slash+1))}</mrow></mfrac>`;return `<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline" aria-label="${s}"><mrow>${body}</mrow></math>`}
function explanation(s){return s.split(' = ').map(math).join(' = ')}function note(s){ui.toast.textContent=s;toastUntil=performance.now()+4400}
function updatePowers(){ui.speed.textContent=speedTime>0?`⚡ Đang tăng tốc ${Math.ceil(speedTime)}s`:`⚡ Tăng tốc ×${speedCharges}`;ui.shield.textContent=shieldTime>0?`◇ Lá chắn ${Math.ceil(shieldTime)}s`:`◇ Lá chắn ×${shieldCharges}`;ui.speed.disabled=phase!=='playing'||speedCharges===0||speedTime>0;ui.shield.disabled=phase!=='playing'||shieldCharges===0||shieldTime>0;ui.speed.classList.toggle('active',speedTime>0);ui.shield.classList.toggle('active',shieldTime>0)}
function activateSpeed(){if(phase!=='playing'||speedCharges<1||speedTime>0)return;speedCharges--;speedTime=6;updatePowers();music(760,.15);note('Tăng tốc trong 6 giây!')}
function activateShield(){if(phase!=='playing'||shieldCharges<1||shieldTime>0)return;shieldCharges--;shieldTime=8;updatePowers();music(930,.15);note('Lá chắn bảo vệ khỏi một lần quái chạm trong 8 giây.')}
function start(){index=0;correctCount=0;speedCharges=0;shieldCharges=0;prepareStage('Bạn đã sẵn sàng bắt đầu hành trình?')}
function prepareStage(message){phase='ready';spawnStage();ui.title.textContent=`Mê cung ${index+1} / ${questions.length}`;ui.body.textContent=`${message} Màn này bắt đầu với 3 mạng. Có ${enemies.length} quái đuổi theo nhân vật. Bấm nút khi bạn sẵn sàng.`;ui.play.textContent='Bắt đầu màn đấu →';ui.overlay.style.display='flex';updatePowers()}
function launchStage(){if(phase!=='ready')return;phase='playing';invuln=2;ui.overlay.style.display='none';last=performance.now();updatePowers();note('Tìm cổng chứa đáp án đúng!');music(620)}
function finish(win){phase='end';ui.title.textContent=win?'✦ Giải mã thành công!':'Hết 3 mạng · Game Over';ui.body.textContent=win?`Bạn đã hoàn thành ${questions.length} mê cung. Chơi lại để luyện tập nhé.`:`Bạn đã hết ba mạng ở mê cung ${index+1}. Bấm Chơi lại để bắt đầu hành trình mới.`;ui.play.textContent='Chơi lại';ui.overlay.style.display='flex';updatePowers();music(win?900:180,.35,'triangle')}
function takeHit(kind){if(kind==='enemy'&&shieldTime>0){shieldTime=0;invuln=1.2;updatePowers();music(580,.18);note('Lá chắn đã chặn một lần quái chạm!');return}lives--;updateLives();music(190,.22,'triangle');if(lives<=0){finish(false);return}player.x=9.5*T;player.y=6.5*T;invuln=kind==='wrong'?1.4:2.2;wrongDoor=-1;note(kind==='wrong'?`Sai đáp án! Còn ${lives} mạng; hãy thử cổng khác.`:`Bị quái chạm! Còn ${lives} mạng.`)}
function step(dt,now){if(phase!=='playing')return;invuln=Math.max(0,invuln-dt);stageNotice=Math.max(0,stageNotice-dt);const oldSpeed=Math.ceil(speedTime),oldShield=Math.ceil(shieldTime);speedTime=Math.max(0,speedTime-dt);shieldTime=Math.max(0,shieldTime-dt);if(oldSpeed!==Math.ceil(speedTime)||oldShield!==Math.ceil(shieldTime))updatePowers();let dx=Number(keys.has('right'))-Number(keys.has('left'))+joystick.x,dy=Number(keys.has('down'))-Number(keys.has('up'))+joystick.y;if(dx)playerFacing=Math.sign(dx);const m=Math.max(1,Math.hypot(dx,dy));move(player,dx/m*180*(speedTime>0?1.65:1)*dt,dy/m*180*(speedTime>0?1.65:1)*dt);
for(let i=0;i<4;i++){const [x,y]=doors[i];if(Math.hypot(player.x-(x+.5)*T,player.y-(y+.5)*T)<20){if(i===questions[index].answer){const worked=questions[index].work;music(840,.16);correctCount++;index++;if(index>=questions.length){finish(true);return}let reward='Đúng!';if(correctCount%3===0){speedCharges=Math.min(3,speedCharges+1);shieldCharges=Math.min(3,shieldCharges+1);reward='Đúng 3 câu! Nhận 1 lượt Tăng tốc và 1 lượt Lá chắn.'}prepareStage(reward);ui.toast.innerHTML='Chính xác! '+explanation(worked);return}else if(wrongDoor!==i){wrongDoor=i;takeHit('wrong');return}break}}
for(const e of enemies){e.repath-=dt;if(e.repath<=0){let predicted={x:player.x+(e.kind===1?dx*110:0),y:player.y+(e.kind===1?dy*110:0)};if(!cell(...tile(predicted)))predicted=player;e.target=path(e,predicted);e.repath=e.kind===0?.20:e.kind===1?.36:.48}let [tx,ty]=e.target||tile(e),px=(tx+.5)*T,py=(ty+.5)*T;if(tx===Math.floor(player.x/T)&&ty===Math.floor(player.y/T)){px=player.x;py=player.y}let ux=px-e.x,uy=py-e.y,dist=Math.hypot(ux,uy);if(dist<6){e.repath=0}else if(dist){const speed=e.pace*(e.kind===2&&Math.sin(now/430+e.phase)>.3?1.37:1);move(e,ux/dist*Math.min(dist,speed*dt),uy/dist*Math.min(dist,speed*dt),10)}if(invuln<=0&&Math.hypot(player.x-e.x,player.y-e.y)<25){takeHit('enemy');break}}
if(now>toastUntil&&ui.toast.textContent)ui.toast.textContent=''}
function rect(x,y,w,h,r=5){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function drawEnemy(e,t){ctx.save();ctx.translate(e.x,e.y+Math.sin(t/220+e.phase)*2);const c=['#ff849d','#ffcf70','#b99cff'][e.kind];ctx.shadowColor=c;ctx.shadowBlur=14;ctx.fillStyle=c;if(e.kind===0){rect(-13,-12,26,26,9)}else if(e.kind===1){ctx.beginPath();ctx.moveTo(0,-17);ctx.lineTo(15,11);ctx.lineTo(-15,11);ctx.fill()}else{ctx.beginPath();ctx.arc(0,0,14,0,7);ctx.fill()}ctx.shadowBlur=0;ctx.fillStyle='#18243d';ctx.fillRect(-8,-3,5,5);ctx.fillRect(3,-3,5,5);ctx.restore()}
function drawPlayer(t){ctx.save();ctx.translate(player.x,player.y+Math.sin(t/(keys.size?95:380))*1.6);ctx.scale(playerFacing,1);ctx.shadowColor=invuln?'#ffe384':'#80f4ff';ctx.shadowBlur=invuln?28:17;ctx.fillStyle='#76eaff66';ctx.beginPath();ctx.ellipse(0,14,19,6,0,0,7);ctx.fill();ctx.shadowBlur=0;if(shieldTime>0){ctx.strokeStyle='#c4fff1';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-5,23+Math.sin(t/160)*2,0,7);ctx.stroke()}if(speedTime>0){ctx.strokeStyle='#ffe196';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-24,0);ctx.lineTo(-35,-4);ctx.moveTo(-23,7);ctx.lineTo(-32,10);ctx.stroke()}ctx.fillStyle='#20375c';rect(-12,10,9,8,3);rect(4,10,9,8,3);ctx.fillStyle='#5ccddd';rect(-14,-9,28,24,9);ctx.fillStyle='#296a9d';rect(-10,-5,20,19,5);ctx.fillStyle='#f6cba8';ctx.beginPath();ctx.arc(0,-12,10,0,7);ctx.fill();ctx.fillStyle='#213f68';ctx.beginPath();ctx.arc(0,-17,12,Math.PI,Math.PI*2);ctx.lineTo(11,-13);ctx.lineTo(-11,-13);ctx.fill();ctx.fillStyle='#ffe189';rect(-12,-21,24,4,2);ctx.fillStyle='#15233d';ctx.fillRect(-5,-12,3,3);ctx.fillRect(3,-12,3,3);ctx.fillStyle='#f8ffff';ctx.beginPath();ctx.arc(0,-19,3,0,7);ctx.fill();ctx.restore()}
function render(t){ctx.clearRect(0,0,912,624);const bg=ctx.createLinearGradient(0,0,0,624);bg.addColorStop(0,world.floor2);bg.addColorStop(1,world.floor);ctx.fillStyle=bg;ctx.fillRect(0,0,912,624);for(let y=0;y<H;y++)for(let x=0;x<W;x++){const px=x*T,py=y*T;if(grid[y][x]){ctx.fillStyle=(x+y)%2?world.wall:world.wall2;rect(px+2,py+2,T-4,T-4,6);ctx.fillStyle='#d4faff22';ctx.fillRect(px+6,py+5,34,3)}else{ctx.fillStyle=(x+y)%2?world.floor:world.floor2;ctx.fillRect(px,py,T,T);ctx.strokeStyle='#c3eaff1d';ctx.strokeRect(px+.5,py+.5,T-1,T-1)}}
for(const p of particles){let px=p.x+Math.sin(t/750+p.offset)*7,py=p.y+Math.cos(t/620+p.offset)*7;ctx.globalAlpha=.28+.27*Math.sin(t/560+p.offset)**2;ctx.fillStyle=world.particle;ctx.beginPath();if(world.shape===1)ctx.moveTo(px,py-4);if(world.shape===1){ctx.lineTo(px+3,py+3);ctx.lineTo(px-3,py+3);ctx.fill()}else if(world.shape===3){ctx.fillRect(px-1,py-5,2,10);ctx.fillRect(px-5,py-1,10,2)}else if(world.shape===4){ctx.moveTo(px,py-5);ctx.lineTo(px+4,py);ctx.lineTo(px,py+5);ctx.lineTo(px-4,py);ctx.fill()}else if(world.shape===5){ctx.strokeStyle=world.particle;ctx.lineWidth=1.5;ctx.arc(px,py,3+p.s,0,7);ctx.stroke()}else{ctx.arc(px,py,p.s,0,7);ctx.fill()}}ctx.globalAlpha=1;
doors.forEach(([x,y],i)=>{const px=(x+.5)*T,py=(y+.5)*T;ctx.shadowColor=doorColors[i];ctx.shadowBlur=18+Math.sin(t/270+i)*5;ctx.fillStyle=doorColors[i];rect(px-18,py-18,36,36,9);ctx.shadowBlur=0;ctx.fillStyle='#15243a';ctx.font='800 22px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('ABCD'[i],px,py+1);ctx.strokeStyle=doorColors[i];ctx.lineWidth=2;ctx.beginPath();ctx.arc(px,py,23+Math.sin(t/360+i)*2,0,7);ctx.stroke()});for(const e of enemies)drawEnemy(e,t);drawPlayer(t);
ctx.fillStyle='#d9f7ff';ctx.font='800 13px system-ui';ctx.textAlign='left';ctx.textBaseline='top';ctx.fillText(`✦ ${world.name} · MÊ CUNG ${index+1}`,16,13);if(stageNotice>0&&phase==='playing'){ctx.textAlign='center';ctx.font='800 20px system-ui';ctx.fillStyle=world.accent;ctx.fillText('MÊ CUNG MỚI!',456,290)}}
function frame(t){const dt=Math.min((t-last)/1000||0,.045);last=t;nowFrame=t;step(dt,t);render(t);requestAnimationFrame(frame)}
const mapKey={arrowup:'up',w:'up',arrowdown:'down',s:'down',arrowleft:'left',a:'left',arrowright:'right',d:'right'};window.addEventListener('keydown',e=>{let d=mapKey[e.key.toLowerCase()];if(d){e.preventDefault();keys.add(d)}else if(e.key==='Shift'){e.preventDefault();activateSpeed()}else if(e.code==='Space'){e.preventDefault();activateShield()}});window.addEventListener('keyup',e=>{let d=mapKey[e.key.toLowerCase()];if(d)keys.delete(d)});const joystickEl=$('#joystick'),joystickKnob=$('#joystickKnob');
function resetJoystick(){joystick.x=0;joystick.y=0;joystick.pointer=null;joystickKnob.style.transform='translate(-50%,-50%)'}
function updateJoystick(e){const b=joystickEl.getBoundingClientRect(),cx=b.left+b.width/2,cy=b.top+b.height/2,max=Math.min(b.width,b.height)*.32,rx=e.clientX-cx,ry=e.clientY-cy,d=Math.hypot(rx,ry);const limited=Math.min(d,max),fraction=d>0?limited/d:0;joystick.x=d<8?0:rx*fraction/max;joystick.y=d<8?0:ry*fraction/max;joystickKnob.style.transform=`translate(-50%,-50%) translate(${rx*fraction}px,${ry*fraction}px)`}
joystickEl.addEventListener('pointerdown',e=>{if(phase!=='playing'||joystick.pointer!==null)return;e.preventDefault();joystick.pointer=e.pointerId;joystickEl.setPointerCapture(e.pointerId);updateJoystick(e)});
joystickEl.addEventListener('pointermove',e=>{if(joystick.pointer!==e.pointerId)return;e.preventDefault();updateJoystick(e)});
for(const event of ['pointerup','pointercancel','lostpointercapture'])joystickEl.addEventListener(event,e=>{if(joystick.pointer===e.pointerId)resetJoystick()});
window.addEventListener('blur',()=>{keys.clear();resetJoystick()});
function showTeacher(){previousPhase=phase;phase='teacher';keys.clear();resetJoystick();ui.teacherGrid.innerHTML=questions.map((q,i)=>`<article class="teacher-question"><div class="eyebrow">Câu ${i+1} / ${questions.length} · ${q.topic}</div><div class="teacher-prompt">${q.lead} ${math(q.expr)} ?</div><div class="teacher-choices">${q.choices.map((v,k)=>`<div class="teacher-choice" style="border-left:3px solid ${doorColors[k]}"><b>${'ABCD'[k]}.</b> ${math(v)}</div>`).join('')}</div><button type="button" data-answer="${i}" aria-expanded="false">Xem đáp án</button><div class="teacher-answer" id="teacherAnswer${i}" hidden><b>Đúng: ${'ABCD'[q.answer]}.</b> ${math(q.choices[q.answer])}<br><b>Phép biến đổi:</b> ${explanation(q.work)}</div></article>`).join('');ui.teacherPanel.hidden=false;ui.teacherPanel.scrollTop=0;updatePowers()}
function closeTeacher(){ui.teacherPanel.hidden=true;phase=previousPhase;keys.clear();last=performance.now();updatePowers()}
const TEACHER_PASSWORD='05067379';
function openTeacherLogin(){if(phase==='teacher'||phase==='teacher_login')return;previousPhase=phase;phase='teacher_login';keys.clear();resetJoystick();ui.teacherPassword.value='';ui.teacherLoginError.textContent='';ui.teacherLogin.hidden=false;ui.teacherPassword.focus();updatePowers()}
function closeTeacherLogin(){ui.teacherLogin.hidden=true;ui.teacherPassword.value='';ui.teacherLoginError.textContent='';phase=previousPhase;keys.clear();last=performance.now();updatePowers()}
function submitTeacherLogin(e){e.preventDefault();if(ui.teacherPassword.value.trim()!==TEACHER_PASSWORD){ui.teacherLoginError.textContent='Mật khẩu chưa đúng. Vui lòng thử lại.';ui.teacherPassword.select();music(190,.12);return}closeTeacherLogin();showTeacher()}
ui.teacherBtn.addEventListener('click',openTeacherLogin);ui.teacherCancel.addEventListener('click',closeTeacherLogin);ui.teacherLoginForm.addEventListener('submit',submitTeacherLogin);ui.closeTeacher.addEventListener('click',closeTeacher);ui.teacherGrid.addEventListener('click',e=>{const b=e.target.closest('[data-answer]');if(!b)return;const box=$('#teacherAnswer'+b.dataset.answer);box.hidden=!box.hidden;b.textContent=box.hidden?'Xem đáp án':'Ẩn đáp án';b.setAttribute('aria-expanded',String(!box.hidden))});ui.play.addEventListener('click',()=>{if(phase==='ready')launchStage();else start()});ui.speed.addEventListener('click',activateSpeed);ui.shield.addEventListener('click',activateShield);ui.sound.addEventListener('click',()=>{soundOn=!soundOn;ui.sound.textContent='♫ Âm thanh: '+(soundOn?'Bật':'Tắt');if(soundOn)music(600)});
// Build a complete preview before the start screen is dismissed.
spawnStage();requestAnimationFrame(frame);
